trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

resources:
- repo: self

steps: 
- task: Docker@2
  displayName: Build and push
  inputs:
    containerRegistry: '1c2a465f-a03e-46e8-9aac-0d871a865530'
    repository: 'laionapi'
    command: 'buildAndPush'
    Dockerfile: '**/Dockerfile'
    tags: |
      $(Build.BuildId)
      latest
