export const RECEITA_ORGAOS = "RECEITA_ORGAOS";
export const RECEITA_SITUACOES = "RECEITA_SITUACOES";
export const RECEITA_TIPOS_LOTES = "RECEITA_TIPOS_LOTES";
export const RECEITA_UNIDADES_ARMAZENADORAS = "RECEITA_UNIDADES_ARMAZENADORAS";