// Applicaion environments.
export const PORT = "PORT";
export const REQUEST_MAX_COMPLEXITY = "REQUEST_MAX_COMPLEXITY"; 

// Sendgrid environments.
export const SENDGRID_API_KEY = "SENDGRID_API_KEY";
export const SENDGRID_EMAIL_ADDRESS = "SENDGRID_EMAIL_ADDRESS";
export const SENDGRID_SENDER_NAME = "SENDGRID_SENDER_NAME";
export const SENDGRID_TEMPLATE_SUBSCRIBE = "SENDGRID_TEMPLATE_SUBSCRIBE";
export const SENDGRID_TEMPLATE_UPDATE = "SENDGRID_TEMPLATE_UPDATE";

// MongoDB environments.
export const MONGODB_CONNECTION = "MONGODB_CONNECTION";
export const MONGODB_DATABASE = "MONGODB_DATABASE";
